##/software/biosoft/software/python/anaconda3-python3-2018/bin/R
library(Seurat)
library(patchwork)
library(harmony)
data=readRDS("merged_gene_mat.rds")
data=CreateSeuratObject(data)
data$batch=substr(colnames(data),1,6)
data=NormalizeData(data)
data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)
#all.genes <- rownames(data)
data <- ScaleData(data)
print("1")
data <- RunPCA(data, features = VariableFeatures(object = data))
data <- RunHarmony(data, group.by.vars="batch")
saveRDS(data,file="after_cluster_20PC_res0.5_harmony.rds")
data <- FindNeighbors(data, reduction = "harmony", dims = 1:20)
data <- FindClusters(data, resolution = 0.5)
#data <- RunTSNE(data, dims = 1:50, tsne.method = "FIt-SNE", nthreads = 4, max_iter = 2000)
data <- RunUMAP(data, dims = 1:50, label = T,reduction="harmony")
saveRDS(data,file="after_cluster_20PC_res0.5_harmony.rds")

